project:
  type: website
  output-dir: docs

website:
  title: "Luke Talman"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: usdcad_uso.qmd
        text: "USD/CAD USO Quant Model"
      - href: RBOB.qmd
        text: "RBOB Trading"
      - href: AssetClasses.qmd
        text: "Asset Classes"
        
format:
  html:
    theme: Litera
    css: styles.css
    toc: true



