project:
  type: website
  output-dir: docs

website:
  title: "Luke Talman"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: Litera
    css: styles.css
    toc: true



